[package]
name = "interledger-router"
version = "0.1.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Router for Interledger requests"
license = "Apache-2.0"
edition = "2018"

[dependencies]
bytes = "0.4.11"
futures = "0.1.25"
interledger-packet = { path = "../interledger-packet" }
interledger-service = { path = "../interledger-service" }
parking_lot = "0.7.1"