[package]
name = "interledger-packet"
version = "0.1.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Interledger packet serialization/deserialization"
license = "Apache-2.0"
edition = "2018"

[dependencies]
byteorder = "1.2.7"
bytes = "0.4.11"
chrono = "0.4.6"
quick-error = "1.2.2"

[dev-dependencies]
criterion = "0.2.9"
lazy_static = "1.2.0"

[[bench]]
name = "packets"
harness = false
