[workspace]

members = [
  "./crates/interledger-btp",
  "./crates/interledger-http",
  "./crates/interledger-packet",
  "./crates/interledger-router",
  "./crates/interledger-service",
  "./crates/interledger-store-memory",
]
