[package]
name = "interledger"
version = "0.3.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Interledger client library"
license = "Apache-2.0"
edition = "2018"

[lib]
name = "interledger"
path = "src/lib.rs"

[[main]]
name = "interledger"
path = "src/bin.rs"

[dependencies]
base64 = "0.10.1"
ring = "0.14.6"
bytes = "0.4.11"
clap = "2.32.0"
env_logger = "0.6.0"
futures = "0.1.25"
interledger-btp = { path = "../interledger-btp" }
interledger-http = { path = "../interledger-http" }
interledger-router = { path = "../interledger-router" }
interledger-service-util = { path = "../interledger-service-util" }
interledger-spsp = { path = "../interledger-spsp" }
interledger-store-memory = { path = "../interledger-store-memory" }
tokio = "0.1.15"
url = "1.7.2"

[badges]
circle-ci = { repository = "emschwartz/interledger-rs" }
codecov = { repository = "emschwartz/interledger-rs" }
