[package]
name = "interledger-ildcp"
version = "0.1.0"
authors = ["Evan Schwartz <evan@ripple.com>"]
description = "Implementation of the Interledger Dynamic Configuration Protocol (ILDCP)"
license = "Apache-2.0"
edition = "2018"

[dependencies]
bytes = "0.4.11"
byteorder = "1.3.1"
futures = "0.1.25"
interledger-packet = { path = "../interledger-packet" }
interledger-service = { path = "../interledger-service" }
lazy_static = "1.2.0"
